theme: minima
title: Simple and delicious cooking site
author: saschayukio
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  simple cooking recipes for all purposes

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
